#!/bin/bash

ROOT_PATH="$(realpath "$( dirname "${BASH_SOURCE[0]}" )")"

# strict mode
set -euo pipefail
IFS=$'\n\t'

# run code
code "--extensions-dir=$ROOT_PATH/.vscode-env/extensions" "--user-data-dir=$ROOT_PATH/.vscode-env/userdata" "$@"
